import { Roboto  } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={roboto.className}>
      {/* <div>
        <ul>
          <li>
            <Link href="signup">Create New Account</Link>
          </li>
          <li></li>
        </ul>
      </div> */}
        {children}
      </body>
    </html>
  );
}
