import { Roboto } from "next/font/google";
import "./globals.css";
import ToastProvider from "../components/ToastProvider";

import jwt from "jsonwebtoken";
import { cookies, headers } from "next/headers";
import { getCurrentUser } from "../ulits/getUser";

import { UserProvider } from "../context/UserContext";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  let currentUser = null;

  const cookieStore = await cookies();
  const token = cookieStore.get("authToken")?.value;

  if (token) {
    try {
      const decoded = jwt.verify(token, process.env.JWT_SECRET);
      currentUser = await getCurrentUser(decoded.userId);
    } catch (err) {
      currentUser = null;
    }
  }

  return (
    <html lang="en">
      <body className={roboto.className}>
        <UserProvider value={currentUser}>
       {children}
       <ToastProvider />
        </UserProvider>
      </body>
    </html>
  );
}
