import { Roboto } from "next/font/google";
import "./globals.css";
import ToastProvider from "../components/ToastProvider";
import { FaAngleLeft } from "react-icons/fa6";
import jwt from "jsonwebtoken";
import { cookies, headers } from "next/headers";
import { getCurrentUser } from "../ulits/getUser";

import { UserProvider } from "../context/UserContext";
import Sidebar from "../components/HomePage/Sidebar";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,pageTitle  }) {
  let currentUser = null;

  const cookieStore = await cookies();
  const token = cookieStore.get("authToken")?.value;

  if (token) {
    try {
      const decoded = jwt.verify(token, process.env.JWT_SECRET);
      currentUser = await getCurrentUser(decoded.userId);
    } catch (err) {
      currentUser = null;
    }
  }
  return (
    <html lang="en">
      <body className={roboto.className}>
        <UserProvider value={currentUser}>

          <section className="flex flex-col lg:flex-row w-full gap-7 pt-2">
            <div className=" h-full w-1/5 bg-white shadow-xl px-6 ">
              <Sidebar />
            </div>
            <div className="w-4/5 px-6 pt-5">
              {/* <Header/> */}
              {children}
            </div>
          </section>

          <ToastProvider />

        </UserProvider>
      </body>
    </html>
  );
}
